---
- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Reload systemd
  command: systemctl daemon-reexec

- name: Restart Flask
  systemd:
    name: flask
    state: restarted
