---
- name: Update apt cache
  apt:
    update_cache: true

- name: Upgrade system packages
  apt:
    upgrade: dist

- name: Install Grafana dependencies
  apt:
    name:
      - adduser
      - libfontconfig1
      - musl
    state: present

- name: Download Grafana Enterprise package
  get_url:
    url: "{{ grafana_download_url }}"
    dest: "/tmp/{{ grafana_package }}"
    mode: "0644"

- name: Install Grafana Enterprise
  apt:
    deb: "/tmp/{{ grafana_package }}"
  notify: Restart Grafana

- name: Deploy Grafana config
  template:
    src: {{ item }}
    dest: "/etc/grafana/provisioning/datasources/{{ item | regex_replace('\\.j2$', '') }}"
  loop:
    - prometheus.yml.j2
    - loki.yml.j2
  notify: Restart Grafana


- name: Enable and start Grafana service
  systemd:
    name: grafana-server
    enabled: true
    state: started
