---
- name: Install packages
  apt:
    name:
      - nginx
      - nano
      - vim
      - python3
      - python3-pip
      - python3-venv
      - mariadb-client
      - libmariadb-dev
      - build-essential      
    state: present
    update_cache: yes

- name: Create virtualenv
  command: python3 -m venv /opt/flaskenv
  args:
    creates: /opt/flaskenv

- name: Install Flask
  command: /opt/flaskenv/bin/pip install flask
  notify: Restart Flask    

- name: Deploy Flask app from template
  template:
    src: app.py.j2
    dest: /root/app.py
  notify: Restart Flask

- name: Create systemd service
  copy:
    dest: /etc/systemd/system/flask.service
    content: |
      [Unit]
      Description=Flask App
      After=network.target

      [Service]
      User=root
      WorkingDirectory=/root
      ExecStart=/opt/flaskenv/bin/python /root/app.py
      Restart=always

      [Install]
      WantedBy=multi-user.target
  notify:
    - Reload systemd
    - Restart Flask

- name: Enable Flask
  systemd:
    name: flask
    enabled: yes

- name: Deploy nginx site config
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart nginx

- name: Enable nginx site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
    force: yes

- name: Copy website files
  copy:
    src: "{{ item }}"
    dest: "/var/www/html/{{ item }}"
    owner: www-data
    group: www-data
    mode: '0644'
  loop:
    - index.html
    - style.css

- name: Ensure nginx is running
  systemd:
    name: nginx
    state: started
    enabled: yes
