---
- name: Create prometheus group
  group:
    name: "{{ node_group }}"
    system: true

- name: Create prometheus user
  user:
    name: "{{ node_user }}"
    group: "{{ node_group }}"
    system: true
    shell: /usr/sbin/nologin
    create_home: false

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ node_user }}"
    group: "{{ node_group }}"
    mode: "0775"
  loop:
    - "{{ node_data_dir }}"
    - "{{ node_tmp_dir }}"

- name: Download Node Exporter archive
  get_url:
    url: "{{ node_download_url }}"
    dest: "{{ node_tmp_dir }}/node_exporter-{{ node_version }}.linux-amd64.tar.gz"
    mode: "0644"

- name: Extract Node Exporter archive
  unarchive:
    src: "{{ node_tmp_dir }}/node_exporter-{{ node_version }}.linux-amd64.tar.gz"
    dest: "{{ node_tmp_dir }}"
    remote_src: true #This flasg on true => src folder is already on the server side (ec2), default is on the ansible ec2
    creates: "{{ node_tmp_dir }}/node_exporter-{{ node_version }}.linux-amd64"

- name: Install Node Exporter binary
  copy:
    src: "{{ node_tmp_dir }}/node_exporter-{{ node_version }}.linux-amd64/node_exporter"
    dest: "{{ node_data_dir }}/node_exporter"
    owner: "{{ node_user }}"
    group: "{{ node_group }}"
    mode: "0755"
    remote_src: true #This flasg on true => src folder is already on the server side (ec2), default is on the ansible ec2
  notify: restart node exporter

- name: Deploy Node Exporter systemd service
  template:
    src: node.service.j2
    dest: /etc/systemd/system/{{ node_service_name }}.service
    mode: "0644"
  notify:
    - reload systemd
    - restart node exporter

- name: Enable and start Node Exporter
  systemd:
    name: "{{ node_service_name }}"
    enabled: true
    state: started
