---
- name: Deploy application
  hosts: flask
  become: yes
  roles:
    - flask

- name: Install Grafana
  hosts: grafana
  become: yes
  roles:
    - grafana

- name: Install Prometheus
  hosts: prometheus
  become: yes
  roles:
    - prometheus
    
- name: Install Loki
  hosts: prometheus
  become: yes
  roles:
    - loki

- name: Install Node
  hosts: flask
  become: yes
  roles:
    - node

